In [20]:
#Perkenalkan Kami Dari Kelompok 3 Menggunakan Modeling Klasifikasi Dengan Model KNN Dan SVM,
#Dibawah Ini Penjelasan Tentang Modeling Yang Kami Gunakan Sebagai Berikut:

#Library Numpy, Berfungsi Melakukan Operasi Proses Komputasi Tipe Data Numerik
#Library Pandas, Berfungsi Menyiadakan Struktur Data & Analisa Sebuah Data Yang Digunakan
#Library Matplotlib, Berfungsi Membuat Table & Grafif Untuk Analasisa Sebuah Data Yang Digunakan
#Library Klasisfikasi Nearest Neighbor(KNN), Berfungsi Membuat Klasifikasi Pada Data Yang Akan 
#Digunakan Akan Mendapat Table Grafik Efisiensi Komputasi & Akurasi Yang Baik


In [21]:
#Libraly python yang akan digunakan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
# Untuk Memasukan Csv pada Data Kanker
DK = pd.read_csv("DataKanker.csv")

#Menampilkan Data CSV Table Di Python
DK.head()

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP_1  Positif_Negative  
0  417.114                 1  
1  468.786                 1  
2  554.697                 1  
3  928.220                 1  
4  773.920                 1

In [23]:
# Memberikan Informasi Type Data Yang Digunakan DiPython
DK.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Age               116 non-null    int64  
 1   BMI               116 non-null    float64
 2   Glucose           116 non-null    int64  
 3   Insulin           116 non-null    float64
 4   HOMA              116 non-null    float64
 5   Leptin            116 non-null    float64
 6   Adiponectin       116 non-null    float64
 7   Resistin          116 non-null    float64
 8   MCP_1             116 non-null    float64
 9   Positif_Negative  116 non-null    int64  
dtypes: float64(7), int64(3)
memory usage: 9.2 KB


In [24]:
#Dibawah Ini Pada Data Kanker Menggunakan Data X & Data Y Sebagai Berikut:

#Untuk Data X, Sebagai DK_x Terdiri Dari: 'Leptin', 'BMI','HOMA'
#Untuk Data Y, Sebagai DK_y Terdiri Dari: 'Positif_Negative'

In [25]:
# Menampilkan DK_x pada table di csv yang akan digunakan
DK_x = DK[['Leptin', 'BMI','HOMA']]
DK_x.head

<bound method NDFrame.head of       Leptin        BMI      HOMA
0     8.8071  23.500000  0.467409
1     8.8438  20.690495  0.706897
2    17.9393  23.124670  1.009651
3     9.8827  21.367521  0.612725
4     6.6994  21.111111  0.805386
..       ...        ...       ...
111  54.6800  26.850000  0.755688
112  12.4500  26.840000  1.117400
113  61.4800  32.050000  1.370998
114  24.9600  25.590000  0.570392
115  90.2800  27.180000  6.777364

[116 rows x 3 columns]>

In [26]:
# Menampilkan DK_y pada table di csv yang akan digunakan
DK_y = DK[['Positif_Negative']]
DK_y.head

<bound method NDFrame.head of      Positif_Negative
0                   1
1                   1
2                   1
3                   1
4                   1
..                ...
111                 2
112                 2
113                 2
114                 2
115                 2

[116 rows x 1 columns]>

In [27]:
#Dibawah Ini Pada Data X & Data Y Pada Train & Test Data Kanker Menggunakan 50%
#Dan Random 70% Yang Digunakan:

#Untuk Data X Pada Data Kanker Di Train & Test, Diberi Nama Sebagai berikut: DK_x_train & DK_x_test
#Untuk Data y Pada Data Kanker Di Train & Test, Diberi Nama Sebagai berikut: DK_y_train & DK_y_test

In [28]:
from sklearn.model_selection import train_test_split

# Untuk Memberikan Training dan Testing pada Data Kanker tersebut dengan train Dan test 50% & Random State 70%
x_train, x_test, y_train, y_test = train_test_split(DK_x, DK_y, test_size = 0.5, random_state = 70)

In [29]:
#Dibawah Ini Menjelaskan Library Preprocessing Pada StandardScaler Sebagai Berikut:

#Preprocessing Pada StandardScaler, Berfungsi Mengaktifkan Package Untuk
#Standalisasi Pada Kolom DiData Digunakan

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()  
scaler.fit(x_train)
x_train = scaler.transform(x_train)  
x_test = scaler.transform(x_test)

In [31]:
#Library Pada Klasifikasi
from sklearn.neighbors import KNeighborsClassifier

#KNeighborsClassifier
modelKNN = KNeighborsClassifier(n_neighbors=4)
modelKNN.fit(x_train, y_train)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=4, p=2,
           weights='uniform')

In [32]:
#Dibawah Ini Pada Prediksi Modeling Klasifikasi Yang Digunakan Sebagai Berikut:

#Untuk Modeling Klasisfikasi Nearest Neighbor(KNN), Diberi Nama Sebagai KNR_pred

In [33]:
# Untuk Memberikan Prediksi Pada modeKNR Pada Data Kanker X Pada Test
y_pred = modelKNN.predict(x_test)
y_pred

array([1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1,
       2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1])

In [34]:
#Dibawah Ini Menjelaskan Modeling Knn Untuk Memberikan Probalitas Pada Prediksi
# Data X & Data Y Test Sebagai Berikut:

#Prediksi Pada Modeling Probalitas Data X, Diberi Nama: x_test
#Prediksi Pada Modeling Probalitas Data Y Dengan menggunakan Matrik, Diberi Nama: y_test

In [35]:
modelKNN.predict_proba(x_test)

array([[0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.25, 0.75],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.25, 0.75],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.25, 0.75],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.25, 0.75],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.25, 0.75],
       [0.25, 0.75],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.25, 0.75],
       [0.5 , 0.5 ],
       [0.25, 0.75],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.25, 0.75],
       [0.25, 0.75],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.25,

In [36]:
#Dibawah Ini Mnjlskan Modeling Knn Untuk Memberikan Probalitas Pada Prediksi DiMatrik Sbagai Brkut:

# Matrik Pada Obejk classification_report, confusion_matrix, Berfungsi
#Memberikan Suatu Bilangan, Simbol Yang Akan Digunakan

In [37]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[19  9]
 [16 14]]


In [38]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.54      0.68      0.60        28
           2       0.61      0.47      0.53        30

   micro avg       0.57      0.57      0.57        58
   macro avg       0.58      0.57      0.57        58
weighted avg       0.58      0.57      0.56        58

